services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: ChangeME!
      POSTGRES_DB: hello_world
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - hello-world

volumes:
  pgdata:

networks:
  hello-world: